title: <p align="center"> Hazel Nguyen </p>
logo: "/images/round_logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  A Data Newbie's Journey
  <br><br>
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/hazelwen/">Linkedin</a> |
  <a href="https://github.com/hazel-nguyen">Github</a> 
  </p>
  
  
  <p align="justify">
  Hazel's here \^o^/ I'm a senior double majoring in Finance and Data Science at Miami University in Ohio
  <br><br>
  I'm currently seeking full-time roles in data science and analytics
  <br><br>

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: dark
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
